### ISSUE TITLE
Add slides about project structure

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/rin3-fall-2024#3]

**Comment by dgkeyes** [comment]
Add to week 1 slides

**Comment by dgkeyes** [comment]
@graciellehigino is this done? I can't remember

**Comment by graciellehigino** [comment]
Yeah, I think we just needed to render it! I wasn't able to render on my end because the code accesses your Google account =D

**Comment by dgkeyes** [comment]
All set, thanks! The only thing I changed was calling the section you added How to Organize Your Files in R in 3 Months, which is also what I renamed the lesson. However, the lesson isn't currently visible, but I will make it visible during week 1.
